// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Chart1;
void ui_event_Panel3(lv_event_t * e);
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_targetLbl;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_responseLbl;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
void ui_event_Panel5(lv_event_t * e);
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label12;
void ui_event_Spinner1(lv_event_t * e);
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_ssidLbl;
extern lv_obj_t * ui_statusLbl;
extern lv_obj_t * ui_ipLbl;
extern lv_obj_t * ui_macLbl;
extern lv_obj_t * ui_subnetLbl;
extern lv_obj_t * ui_gatewayLbl;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_largeRSSI;
void ui_event_Panel16(lv_event_t * e);
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Keyboard1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label24;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_TextArea3;
void ui_event_TextArea4(lv_event_t * e);
extern lv_obj_t * ui_TextArea4;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1215908228);    // assets\Dakirby309-Simply-Styled-YouTube.72.png
LV_IMG_DECLARE(ui_img_948428005);    // assets\Alecive-Flatwoken-Apps-Dialog-Refresh.48.png
LV_IMG_DECLARE(ui_img_1537602657);    // assets\Dakirby309-Simply-Styled-YouTube.64.png
LV_IMG_DECLARE(ui_img_60311142);    // assets\Flat-Icons.com-Square-Power.96.png
LV_IMG_DECLARE(ui_img_1215043413);    // assets\Alecive-Flatwoken-Apps-Dialog-Refresh.64.png

LV_FONT_DECLARE(ui_font_Large);
LV_FONT_DECLARE(ui_font_midFont);
LV_FONT_DECLARE(ui_font_MIDMID);
LV_FONT_DECLARE(ui_font_SMALL);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
